# Generated by Django 5.0.4 on 2024-04-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
