# Generated by Django 5.0.4 on 2024-04-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_item_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
