# Generated by Django 5.0.4 on 2024-04-30 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_department_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='department_id',
            new_name='department',
        ),
        migrations.CreateModel(
            name='MovingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('finish_date', models.DateTimeField()),
                ('destination_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_department', to='setup.department')),
                ('initial_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_department', to='setup.department')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='moving_history',
            field=models.ManyToManyField(to='setup.movinghistory'),
        ),
    ]
