# Generated by Django 5.0.4 on 2024-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_alter_item_moving_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='movinghistory',
            name='item_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
