# Generated by Django 5.0.4 on 2024-04-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_movinghistory_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movinghistory',
            name='finish_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
